### ISSUE TITLE
Ubuntu 14.04 package conflict breaks pad_matrix()

### ISSUE THREAD

**Issue by Makman2** [bmc/munkres#13]
Hello :)

I'm working on the ["coala"](https://github.com/coala-analyzer/coala/) project, that uses your munkres algorithms. Our project is a code checking tool that shall allow to check for various code rules.

One of our main features is a code-clone detection tool that uses munkres.

Coming to the problem:
We encountered a bug when using the apt-get package `python3-munkres` only (on Ubuntu 14.04 LTS).
The `pad_matrix` function behaves wrong, we let it pad with `1`, but we get a matrix padded with `0`. But using the pip-package there's no problem.

We use python version 3.

Steps to reproduce (at least for Ubuntu 14.04):
1. Make sure you don't have installed the pip package `munkres`
2. Install the apt-get package `python3-munkres`
3. Clone our git repository at https://github.com/coala-analyzer/coala
4. Run the tests / the fault test: `./run_tests.py -t ClangCloneDetectionBearTest`

The test is located in `bears/tests/codeclone_detection/ClangCloneDetectionBearTest.py`.
This bug is confirmed from our other developers^^

We have already an issue open, see [#586](https://github.com/coala-analyzer/coala/issues/586).

**Comment by addaleax** [comment]
FYI, the fix for this bug was #10 and is included in the 1.0.7 release
