### ISSUE TITLE
meta: doing all changes through PRs

### ISSUE THREAD

**Issue by addaleax** [bmc/munkres#14]
Hi! I am maintaining a [JS port](https://github.com/addaleax/munkres-js) of this package, and while I check this repo from time to time for changes that could be applied downstream, it would be helpful if you’d consider doing most of the changes here through a quick pull request (that can be merged instantly) so that the watchers of this repo can get notifications on changes.

**Comment by bmc** [comment]
I will try to do so moving forward.

**Comment by addaleax** [comment]
Awesome, thanks!

**Comment by bmc** [comment]
Note that I just released 1.0.9, most of which was done via PRs from @kylemcdonald. In case you didn't get a notification, the commits start with 95b7d12.

**Comment by addaleax** [comment]
I’m just going through the commits and backporting everything as far as it applies. :) Again, thanks!
