### ISSUE TITLE
version 1.0.9 on PyPI is missing distribution files?

### ISSUE THREAD

**Issue by anthrotype** [bmc/munkres#21]
Hi @bmc,
thanks for this package!

I noticed that the latest v1.0.9 version that was published to PyPI actually does not contain any distribution files to download:
 
https://pypi.python.org/pypi/munkres/1.0.9

When I do `pip search munkres`, 1.0.9 shows up:
```
munkres (1.0.9)     - munkres algorithm for the Assignment Problem
```

However, when I do `pip install munkres` only 1.0.8 gets installed, not 1.0.9.

Could you please upload the source distribution and wheel packages for 1.0.9?

Thanks

**Comment by anthrotype** [comment]
ping @bmc

**Comment by anthrotype** [comment]
hey @bmc, any chances you could upload a wheel and sdist to PyPI for the 1.0.9 release?
As I said, 1.0.9 is currently missing the files and only has the metadata.
If one attempts to `pip install munkres`, one gets 1.0.8 instead of 1.0.9.
Thank you.

**Comment by bmc** [comment]
Fixed. Finally. Sorry for the delay. Version is now 1.0.10 to reflect changes in `setup.py`.

**Comment by anthrotype** [comment]
Thank you! No problem :)
