### ISSUE TITLE
"print_matrix" always print integral value of cost matrix

### ISSUE THREAD

**Issue by finn0** [bmc/munkres#34]
When I enter cost values in floating point form inside cost matrix, `print_matrix` function treats those values as integer and print only integral part of the values. I run this code:

```python3
from munkres import Munkres, print_matrix

matrix = [[5.1, 9.6, 1.7],
          [10.2, 3.5, 2.8],
          [8.3, 7.4, 4.9]]
m = Munkres()
indexes = m.compute(matrix)
print_matrix(matrix, msg='Lowest cost through this matrix:')
total = 0
for row, column in indexes:
    value = matrix[row][column]
    total += value
    print(f'({row}, {column}) -> {value}')
print(f'total cost: {total}')
```

Output is as follows:

```bash
Lowest cost through this matrix:
[   5,    9,    1]
[  10,    3,    2]
[   8,    7,    4]
(0, 0) -> 5.1
(1, 1) -> 3.5
(2, 2) -> 4.9
total cost: 13.5
```

See matrix printed by `print_matrix` function isn't same matrix as given in code that's it only has integral part with them, although total cost calculation is correct. Is it a expected behavior of `print_matrix` function? Because it's not always the case, cost matrix would have all value in integral form.

**Comment by finn0** [comment]
I think this can be fixed by replacing 'd' with 's' in line [L#517](https://github.com/bmc/munkres/blob/master/munkres.py#L517), or even when can remove whole if/else loop and replace it with single statement `formatted = ((format + 's') % val)`. If you're agree, I can make a pull request for this.

**Comment by finn0** [comment]
@bmc, sorry for directly pinging you. Can you comment something on this issue? I would like to fix this issue.

**Comment by bmc** [comment]
Sorry. I haven't used this package myself in years. I'm find with the fix. I'll merge any PR and upload again to PyPI.
