### ISSUE TITLE
Broken HTML Link

### ISSUE THREAD

**Issue by jdowner** [bmc/munkres#4]
It looks like the HTML page described in the documentation (http://www.public.iastate.edu/~ddoty/HungarianAlgorithm.html) has been taken down.

**Comment by kylemcdonald** [comment]
The new url is: http://csclab.murraystate.edu/~bob.pilgrim/445/munkres.html

Alternatively, this link should be operational indefinitely: https://web.archive.org/web/20081010092314/http://www.public.iastate.edu/~ddoty/HungarianAlgorithm.html

**Comment by bmc** [comment]
Fixed in version 1.0.9
